In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

In [30]:
df = pd.read_csv('/workspaces/SML/SML /Exp 10/covtype.csv')

In [31]:
df.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5

In [32]:
df.columns

Index(['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology',
       'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways',
       'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1',
       'Wilderness_Area2', 'Wilderness_Area3', 'Wilderness_Area4',
       'Soil_Type1', 'Soil_Type2', 'Soil_Type3', 'Soil_Type4', 'Soil_Type5',
       'Soil_Type6', 'Soil_Type7', 'Soil_Type8', 'Soil_Type9', 'Soil_Type10',
       'Soil_Type11', 'Soil_Type12', 'Soil_Type13', 'Soil_Type14',
       'Soil_Type15', 'Soil_Type16', 'Soil_Type17', 'Soil_Type18',
       'Soil_Type19', 'Soil_Type20', 'Soil_Type21', 'Soil_Type22',
       'Soil_Type23', 'Soil_Type24', 'Soil_Type25', 'Soil_Type26',
       'Soil_Type27', 'Soil_Type28', 'Soil_Type29', 'Soil_Type30',
       'Soil_Type31', 'Soil_Type32', 'Soil_Type33', 'Soil_Type34',
       'Soil_Type35', 'Soil_Type36', 'Soil_Type37', 'Soil_Type38',
       'Soil_Type39', 'Soil_Type40', 'Cover_Type'],
      dtype='str')

In [33]:
df =pd.get_dummies(df)
df.head(5)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5

In [34]:
x = df.drop('Cover_Type',axis=1)
y = df.iloc[:,-1]

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,random_state=42,test_size=0.25)

In [39]:
rg = RandomForestRegressor(n_estimators=50,random_state=42)

In [40]:
rg.fit(x_train,y_train)

KeyboardInterrupt:

In [ ]:
y_pred = rg.predict(x_test)

In [ ]:
from sklearn.tree import export_graphviz
import pydot
df_list = list(df.columns)
tree = rg.estimators_[5]
#export the image to a dot file
export_graphviz(tree,out_file='tree.dot',feature_names=df_list,rounded=True,precision=1)

#use dot file to create graph

(graph, ) = pydot.graph_from_dot_file('tree1.dot')

graph.write_png('tree1.png')

NameError: name 'rg' is not defined

In [ ]:
from sklearn.tree import export_graphviz
import pydot

rf_small=RandomForestRegressor(n_estimators=10,max_depth=3,random_state=42)
rf_small.fit(x_train,y_train)
tree_small=rf_small.estimators_[5]

export_graphviz(tree_small,out_file='small_tree.dot',feature_names=df_list,rounded=True,precision=1)
(graph,)=pydot.graph_from_dot_file('small_tree1.dot')
graph.write_png('small_tree.png');

In [ ]:
importances=list(rg.feature_importances_)
feature_importances=[(feature,round(importance,2)) for feature,importance in zip(df_list,importances)]
feature_importances=sorted(feature_importances,key=lambda x:x[1],reverse=True)
[print ('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('fivethirtyeight')
x_values=list(range(len(importances)))
plt.bar(x_values,importances,orientation='vertical')
plt.xticks(x_values,df_list,rotation='vertical')
plt.ylabel('Importance')
plt.xlabel('Variable')

In [ ]:
import datetime

months = df[:,df_list.index('month')]
days = df[:,df_list.index('day')]   
years = df[:,df_list.index('year')]

dates = [str(int(year)) + '-' + str(int(month)) + '-' + str(int(day)) for year, month, day in zip(years, months, days)]
dates = [datetime.datetime.strptime(date, '%Y-%m-%d') for date in dates]

true_data = pd.DataFrame(data = {'date': dates, 'actual': y_train})

months_test = x_test[:, df_list.index('month')]
days_test = x_test[:, df_list.index('day')]
years_test = x_test[:, df_list.index('year')]

dates_test = [str(int(year)) + '-' + str(int(month)) + '-' + str(int(day)) for year, month, day in zip(years_test, months_test, days_test)]
dates_test = [datetime.datetime.strptime(date, '%Y-%m-%d') for date in dates_test]

predicted_data = pd.DataFrame(data={'date': dates_test, 'predicted': y_pred})